[features]
resolution = true
skip-lint = false

[programs.localnet]
oseme_group = "GrpABCDEFGHIJKLMNOPQRSTUVWXYZ123456789abcdef"
oseme_trust = "TrustXYZ123456789abcdefghijklmnopqrstuvwxyz"
oseme_treasury = "TreasuryABCDEFGHIJKLMNOPQRSTUVWXYZ123456"

[programs.devnet]
oseme_group = "GrpABCDEFGHIJKLMNOPQRSTUVWXYZ123456789abcdef"
oseme_trust = "TrustXYZ123456789abcdefghijklmnopqrstuvwxyz"
oseme_treasury = "TreasuryABCDEFGHIJKLMNOPQRSTUVWXYZ123456"

[programs.mainnet]
oseme_group = "GrpABCDEFGHIJKLMNOPQRSTUVWXYZ123456789abcdef"
oseme_trust = "TrustXYZ123456789abcdefghijklmnopqrstuvwxyz"
oseme_treasury = "TreasuryABCDEFGHIJKLMNOPQRSTUVWXYZ123456"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
  "programs/oseme-group",
  "programs/oseme-trust", 
  "programs/oseme-treasury"
]
